{"name":"Finite\\Exception\\FactoryException","line":10,"short_desc":"A exception throws from a factory","long_desc":"","hint":null,"tags":{"author":[["Yohan","Giarelli","<yohan@frequence-web.fr>"]]},"namespace":"Finite\\Exception","file":"\/Users\/yohan\/Sites\/Finite\/src\/Finite\/Exception\/FactoryException.php","hash":"525a1c3ed419aae7a8d1f10def64370cfcbb841c","parent":"Finite\\Exception\\Exception","modifiers":0,"is_interface":false,"aliases":[],"interfaces":[],"properties":[],"methods":[],"constants":[]}